# Settings are inspired by
# https://github.com/patrick-kidger/equinox/blob/main/mkdocs.yml
site_name: Exponax
site_description: Fast & Differentiable PDE solvers in JAX.
site_author: Felix Koehler
site_url: https://fkoehler.site/exponax

repo_url: https://github.com/Ceyron/exponax
repo_name: Ceyron/exponax
edit_uri: ""  # No edit button

theme:
    name: material
    features:
        - navigation.sections
        - header.autohide  # header disappears as you scroll
        # - navigation.top  # render button to quickly scroll up
    palette:
        - scheme: default
          primary: teal
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: teal
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
    logo: "imgs/logo.svg" # Logo in top left
    favicon: "imgs/logo.svg"  # Favicon in browser tab

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/felix_m_koehler
    - icon: fontawesome/brands/github
      link: https://github.com/ceyron
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@MachineLearningSimulation


strict: true  # Don't allow warnings during the build process

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences:  # Seems to enable syntax highlighting when used with the Material theme.
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search  # requires re-enabling
    - autorefs  # Cross-links to headings
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                options:
                    inherited_members: true  # Allow looking up inherited methods
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    separate_signature: true
                    show_source: true  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4
                    show_symbol_type_heading: true
                    docstring_style: null

nav:
    - 'index.md'
    - Examples:
        - Basics:
            - 1D Advection: 'examples/simple_advection_example_1d.ipynb'
            - 1D Solver Showcase: 'examples/solver_showcase_1d.ipynb'
            - 1D Initial Condition Showcase: 'examples/initial_condition_showcase_1d.ipynb'
            - Basics on Metrics: 'examples/on_metrics_simple.ipynb' 
            - Understanding General and Normalized Stepper: 'examples/understanding_general_and_normalized_stepper.ipynb'
            - Subclassing a custom Solver: 'examples/creating_your_own_solvers_1d.ipynb'
            - 2D Advection: 'examples/simple_advection_example_2d.ipynb'
            - 2D Solver Showcase: 'examples/solver_showcase_2d.ipynb'
            - 3D Solver Showcase: 'examples/solver_showcase_3d.ipynb'
        - Advanced:
            - 1D Burgers Emulator Training: 'examples/learning_burgers_autoregressive_neural_operator.ipynb'
            - More on Metrics: 'examples/on_metrics_advanced.ipynb'
            - 3D Navier-Stokes with Isotropic Turbulence: 'examples/kolmogorov_flow_3d_with_spectral_analysis.ipynb'
        - Additional:
            - Nice Features: 'examples/additional_features.ipynb'
            - Performance Hints: 'examples/performance_hints.ipynb'
        - Awesome List: 'awesome-list.md'
    - Stepper:
        - Overview: 'api/stepper/overview.md'
        - Linear:
            - Advection: 'api/stepper/linear/advection.md'
            - Diffusion: 'api/stepper/linear/diffusion.md'
            - Advection-Diffusion: 'api/stepper/linear/advection_diffusion.md'
            - Dispersion: 'api/stepper/linear/dispersion.md'
            - Hyper-Diffusion: 'api/stepper/linear/hyper_diffusion.md'
            - Wave: 'api/stepper/linear/wave.md'
        - Nonlinear:
            - Burgers: 'api/stepper/nonlinear/burgers.md'
            - Korteweg-de Vries: 'api/stepper/nonlinear/kdv.md'
            - Kuramoto-Sivashinsky: 'api/stepper/nonlinear/ks.md'
            - Kuramoto-Sivashinsky (Conservative): 'api/stepper/nonlinear/ks_cons.md'
            - Navier-Stokes: 'api/stepper/nonlinear/navier_stokes.md'
        - Reaction:
            - Fisher-KPP: 'api/stepper/reaction/fisher_kpp.md'
            - Allen-Cahn: 'api/stepper/reaction/allen_cahn.md'
            - Cahn-Hilliard: 'api/stepper/reaction/cahn_hilliard.md'
            - Swift-Hohenberg: 'api/stepper/reaction/swift_hohenberg.md'
            - Gray-Scott: 'api/stepper/reaction/gray_scott.md'
        - Generic:
            - Physical:
                - General Linear: 'api/stepper/generic/physical/general_linear.md'
                - General Convection: 'api/stepper/generic/physical/general_convection.md'
                - General Gradient Norm: 'api/stepper/generic/physical/general_gradient_norm.md'
                - General Polynomial: 'api/stepper/generic/physical/general_polynomial.md'
                - General Nonlinear: 'api/stepper/generic/physical/general_nonlinear.md'
                - General Vorticity Convection: 'api/stepper/generic/physical/general_vorticity_convection.md'
            - Normalized:
                - Linear: 'api/stepper/generic/normalized/normalized_linear.md'
                - Convection: 'api/stepper/generic/normalized/normalized_convection.md'
                - Gradient Norm: 'api/stepper/generic/normalized/normalized_gradient_norm.md'
                - Polynomial: 'api/stepper/generic/normalized/normalized_polynomial.md'
                - Nonlinear: 'api/stepper/generic/normalized/normalized_nonlinear.md'
            - Difficulty:
                - Linear: 'api/stepper/generic/difficulty/difficulty_linear.md'
                - Convection: 'api/stepper/generic/difficulty/difficulty_convection.md'
                - Gradient Norm: 'api/stepper/generic/difficulty/difficulty_gradient_norm.md'
                - Polynomial: 'api/stepper/generic/difficulty/difficulty_polynomial.md'
                - Nonlinear: 'api/stepper/generic/difficulty/difficulty_nonlinear.md'
        - Additional:
            - Poisson: 'api/stepper/additional/poisson.md'
    - Utilities:
        - Nonlinear Functions:
            - Zero: 'api/utilities/nonlin_fun/zero.md'
            - Convection: 'api/utilities/nonlin_fun/convection.md'
            - Gradient Norm: 'api/utilities/nonlin_fun/gradient_norm.md'
            - Polynomial: 'api/utilities/nonlin_fun/polynomial.md'
            - Vorticity / Projected Convection: 'api/utilities/nonlin_fun/vorticity_convection.md'
            - Nonlinear: 'api/utilities/nonlin_fun/nonlinear.md'
        - Repeated Stepper: 'api/utilities/repeated_stepper.md'
        - Forced Stepper: 'api/utilities/forced_stepper.md'
        - Initial Conditions:
            - Sine Waves 1d: 'api/utilities/initial_conditions/sine_waves_1d.md'
            - Truncated Fourier Series: 'api/utilities/initial_conditions/truncated_fourier_series.md'
            - Gaussian Random Field: 'api/utilities/initial_conditions/gaussian_random_field.md'
            - Diffused Noise: 'api/utilities/initial_conditions/diffused_noise.md'
            - Gaussian Blob: 'api/utilities/initial_conditions/gaussian_blob.md'
            - Discontinuities: 'api/utilities/initial_conditions/discontinuities.md'
            - Helper: 'api/utilities/initial_conditions/helper.md'
        - Rollout & Repeat: 'api/utilities/rollout_and_repeat.md'
        - Grid Generation: 'api/utilities/grid_generation.md'
        - Derivatives: 'api/utilities/derivatives.md'
        - Spectral: 'api/utilities/spectral.md'
        - Interpolation: 'api/utilities/interpolation.md'
        - Normalized & Difficulty: 'api/utilities/normalized_and_difficulty.md'
        - Metrics:
            - Spatial: 'api/utilities/metrics/spatial.md'
            - Fourier-based: 'api/utilities/metrics/fourier.md'
            - Derivative-based: 'api/utilities/metrics/derivative.md'
            - Correlation: 'api/utilities/metrics/correlation.md'
            - Utilities: 'api/utilities/metrics/utils.md'
        - Visualization:
            - Plot States: 'api/utilities/visualization/plot_states.md'
            - Plot Spatio-Temporal: 'api/utilities/visualization/plot_spatio_temporal.md'
            - Plot States Facet: 'api/utilities/visualization/plot_states_facet.md'
            - Plot Spatio-Temporal Facet: 'api/utilities/visualization/plot_spatio_temporal_facet.md'
            - Animate States: 'api/utilities/visualization/animate_states.md'
            - Animate Spatio-Temporal: 'api/utilities/visualization/animate_spatio_temporal.md'
            - Animate States Facet: 'api/utilities/visualization/animate_states_facet.md'
            - Animate Spatio-Temporal Facet: 'api/utilities/visualization/animate_spatio_temporal_facet.md'
    - Additional API:
        - Base:
            - Base Stepper: 'api/stepper/base_stepper.md'
            - Base Nonlinear Function: 'api/utilities/nonlin_fun/base.md'
            - Base Initial Condition: 'api/utilities/initial_conditions/base_initial_condition.md'
        - ETDRK Backbone: 'api/etdrk_backbone.md'
    - Background:
        - Design Decisions: 'background/design_decisions.md'
